"""
Application-wide constants.
"""

# Session
SESSION_EXPIRY_MINUTES = 30

# Cache TTL (seconds)
DEFAULT_CACHE_TTL = 300
WL_CACHE_TTL = 60
RAC_CACHE_TTL = 120
CONFIRMED_CACHE_TTL = 600

# Search
MAX_DIRECT_RESULTS = 5
MAX_VIA_RESULTS = 5
MAX_ALTERNATE_BOARDING_RESULTS = 8
NEARBY_STATION_RADIUS_KM = 25

# Seat Warning
LOW_SEAT_THRESHOLD = 10

# Circuit Breaker
FAILURE_THRESHOLD = 3
CIRCUIT_TIMEOUT_SECONDS = 60

# Ranking
DIRECT_ROUTE_WEIGHT = 40
SEAT_WEIGHT = 30
DELAY_WEIGHT = 20
PREFERENCE_WEIGHT = 10

# Rate Limiter
MAX_REQUESTS_PER_SESSION = 20